name: PlantCAD_offical
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.14
  - htslib=1.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libgomp=15.2.0
  - wheel=0.45.1
  - openssl=3.6.0
  - xz-tools=5.8.1
  - readline=8.2
  - xz=5.8.1
  - liblzma-devel=5.8.1
  - setuptools=80.9.0
  - xz-gpl-tools=5.8.1
  - libgcc=15.2.0
  - _openmp_mutex=4.5
  - ld_impl_linux-64=2.45
  - libzlib=1.3.1
  - libxcrypt=4.4.36
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - pip=25.3
  - tk=8.6.13
  - libgcc-ng=15.2.0
  - libexpat=2.7.3
  - libuuid=2.41.2
  - ca-certificates=2025.11.12
  - ncurses=6.5
  - zstd=1.5.7
prefix: /home/zhang479/miniforge3/envs/PlantCAD_offical
